export const BUSINESSES = [
  {
    id: "b1",
    name: "Emerald City Coffee Roasters",
    category: "Coffee & Cafes",
    description: "Small-batch coffee roaster in Capitol Hill with single-origin pour-overs and weekend cupping sessions.",
    phone: "(206) 555-0143",
    address: "1418 12th Ave, Capitol Hill",
    views: 4820,
    package: "Premium",
    photo: "img/business/biz-1.webp",
  },
  {
    id: "b2",
    name: "Rainier Kitchen & Bar",
    category: "Restaurants",
    description: "Pacific Northwest comfort food with a rotating seasonal menu and a full bar overlooking the water.",
    phone: "(206) 555-0118",
    address: "2210 Alaskan Way, Downtown",
    views: 3160,
    package: "Lux",
    photo: "img/business/biz-2.webp",
  },
  {
    id: "b3",
    name: "Sound Auto Repair",
    category: "Auto Services",
    description: "Family-owned repair shop specializing in Japanese and domestic makes, same-day diagnostics.",
    phone: "(206) 555-0187",
    address: "5417 Leary Ave NW, Ballard",
    views: 880,
    package: "Standard",
    photo: "img/business/biz-3.webp",
  },
  {
    id: "b4",
    name: "Needle & Fade Barbershop",
    category: "Beauty & Salons",
    description: "Classic cuts and hot towel shaves in Ballard, walk-ins welcome most weekdays.",
    phone: "(206) 555-0129",
    address: "2036 NW Market St, Ballard",
    views: 740,
    package: "Standard",
    photo: "img/business/biz-4.webp",
  },
  {
    id: "b5",
    name: "Elliott Bay Boutique",
    category: "Shopping & Retail",
    description: "Independent clothing store featuring Pacific Northwest designers and vintage finds.",
    phone: "(206) 555-0164",
    address: "1521 First Ave, Downtown",
    views: 2470,
    package: "Lux",
    photo: "img/business/biz-5.webp",
  },
  {
    id: "b6",
    name: "Cascade Fitness Studio",
    category: "Health & Fitness",
    description: "Boutique strength and conditioning studio with small-group classes and personal training.",
    phone: "(206) 555-0152",
    address: "312 Broadway E, Capitol Hill",
    views: 5130,
    package: "Premium",
    photo: "img/business/biz-6.webp",
  },
  {
    id: "b7",
    name: "Fremont Sourdough Bakery",
    category: "Food & Bakeries",
    description: "Wood-fired sourdough and pastries baked fresh daily, known for its weekend cinnamon rolls.",
    phone: "(206) 555-0176",
    address: "3601 Fremont Ave N, Fremont",
    views: 1120,
    package: "Standard",
    photo: "img/business/biz-7.webp",
  },
  {
    id: "b8",
    name: "Pike & Pine Bookshop",
    category: "Shopping & Retail",
    description: "Independent bookstore with a strong local-authors section and a monthly reading club.",
    phone: "(206) 555-0193",
    address: "1633 11th Ave, Capitol Hill",
    views: 960,
    package: "Standard",
    photo: "img/business/biz-8.webp",
  },
  {
    id: "b9",
    name: "Puget Sound Web Studio",
    category: "Professional Services",
    description: "Small web design and branding agency working with local Seattle businesses.",
    phone: "(206) 555-0121",
    address: "500 Yale Ave N, South Lake Union",
    views: 2080,
    package: "Lux",
    photo: "img/business/biz-9.webp",
  },
  {
    id: "b10",
    name: "Blossom & Bay Florist",
    category: "Shopping & Retail",
    description: "Custom floral arrangements and same-day delivery across greater Seattle.",
    phone: "(206) 555-0138",
    address: "7204 Greenwood Ave N, Green Lake",
    views: 640,
    package: "Standard",
    photo: "img/business/biz-10.webp",
  },
  {
    id: "b11",
    name: "Waggin' Waterfront Pet Grooming",
    category: "Pet Services",
    description: "Full-service grooming and nail trims, with a calm, low-stress handling approach.",
    phone: "(206) 555-0147",
    address: "1902 Elliott Ave, Belltown",
    views: 520,
    package: "Standard",
    photo: "img/business/biz-11.webp",
  },
  {
    id: "b12",
    name: "Skyline Brewing Taproom",
    category: "Restaurants",
    description: "Neighborhood taproom with a rotating list of house-brewed ales and a weekly trivia night.",
    phone: "(206) 555-0159",
    address: "2926 First Ave S, SoDo",
    views: 6240,
    package: "Premium",
    photo: "img/business/biz-12.webp",
  },
  {
    id: "b13",
    name: "Evergreen Yoga & Wellness",
    category: "Health & Fitness",
    description: "Vinyasa and restorative classes in a light-filled studio near Green Lake.",
    phone: "(206) 555-0112",
    address: "1815 N 45th St, Wallingford",
    views: 1930,
    package: "Lux",
    photo: "img/business/biz-13.webp",
  },
  {
    id: "b14",
    name: "Duwamish Hardware & Supply",
    category: "Home & Hardware",
    description: "Neighborhood hardware store with expert advice and same-day key cutting.",
    phone: "(206) 555-0184",
    address: "4501 Airport Way S, SoDo",
    views: 810,
    package: "Standard",
    photo: "img/business/biz-14.webp",
  },
  {
    id: "b15",
    name: "Scoop City Creamery",
    category: "Food & Bakeries",
    description: "Small-batch ice cream made with local dairy, with a new flavor every week.",
    phone: "(206) 555-0171",
    address: "612 Queen Anne Ave N, Queen Anne",
    views: 2650,
    package: "Lux",
    photo: "img/business/biz-15.webp",
  },
];

export const BUSINESS_CATEGORIES = [...new Set(BUSINESSES.map((b) => b.category))].sort();
