// Вакансии для раздела Jobs. Фотографий нет намеренно: список должностей
// читается быстрее без них, и это снимает нагрузку с и без того небольших
// пулов картинок.

export const JOB_LISTINGS = [
  {
    id: "j1",
    title: "Barista — Morning Shift",
    company: "Emerald City Coffee Roasters",
    category: "Hospitality",
    type: "Part-time",
    salary: "$22–25/hr",
    neighborhood: "Capitol Hill",
    postedAt: "2026-09-23T08:10:00",
    description: "Opening shifts Tuesday through Saturday, pour-over and espresso experience preferred but we train.",
  },
  {
    id: "j2",
    title: "Line Cook",
    company: "Rainier Kitchen & Bar",
    category: "Hospitality",
    type: "Full-time",
    salary: "$26–30/hr",
    neighborhood: "South Lake Union",
    postedAt: "2026-09-23T06:40:00",
    description: "Seasonal menu, scratch kitchen, four-day week. Two years on a hot line required.",
  },
  {
    id: "j3",
    title: "Front-End Developer",
    company: "Puget Digital",
    category: "Tech",
    type: "Full-time",
    salary: "$115k–140k",
    neighborhood: "Belltown",
    postedAt: "2026-09-22T15:20:00",
    description: "React and TypeScript, hybrid two days a week downtown. Accessibility work is a real part of the role.",
  },
  {
    id: "j4",
    title: "Automotive Technician",
    company: "Sound Auto Repair",
    category: "Trades",
    type: "Full-time",
    salary: "$32–38/hr",
    neighborhood: "Ballard",
    postedAt: "2026-09-22T11:05:00",
    description: "Japanese and domestic makes, ASE certification paid for after ninety days.",
  },
  {
    id: "j5",
    title: "Registered Nurse — Urgent Care",
    company: "Cascade Family Health",
    category: "Healthcare",
    type: "Full-time",
    salary: "$48–56/hr",
    neighborhood: "Northgate",
    postedAt: "2026-09-22T09:00:00",
    description: "Three twelve-hour shifts, urgent care floor. Washington RN license required.",
  },
  {
    id: "j6",
    title: "Retail Sales Associate",
    company: "Pike Outfitters",
    category: "Retail",
    type: "Part-time",
    salary: "$21–23/hr",
    neighborhood: "Downtown",
    postedAt: "2026-09-21T17:30:00",
    description: "Weekend coverage in the outdoor gear department, employee discount from day one.",
  },
  {
    id: "j7",
    title: "Bookkeeper",
    company: "Wallingford Accounting Group",
    category: "Office",
    type: "Contract",
    salary: "$35–42/hr",
    neighborhood: "Wallingford",
    postedAt: "2026-09-21T13:15:00",
    description: "Six-month contract covering a parental leave, QuickBooks and payroll reconciliation.",
  },
  {
    id: "j8",
    title: "Preschool Teacher",
    company: "Green Lake Learning Co-op",
    category: "Education",
    type: "Full-time",
    salary: "$27–31/hr",
    neighborhood: "Green Lake",
    postedAt: "2026-09-20T10:45:00",
    description: "Mixed-age classroom, sixteen children, two aides. ECE credits preferred.",
  },
  {
    id: "j9",
    title: "Delivery Driver — Box Truck",
    company: "Harbor Freight Logistics",
    category: "Transport",
    type: "Full-time",
    salary: "$25–28/hr",
    neighborhood: "SoDo",
    postedAt: "2026-09-20T07:20:00",
    description: "Local routes only, home every night. Clean record and a year of box-truck experience.",
  },
  {
    id: "j10",
    title: "Groomer",
    company: "Emerald Paws Grooming",
    category: "Trades",
    type: "Part-time",
    salary: "$24–29/hr",
    neighborhood: "Fremont",
    postedAt: "2026-09-19T16:00:00",
    description: "Four days a week, established client book, commission on top of base.",
  },
  {
    id: "j11",
    title: "Data Analyst",
    company: "Puget Digital",
    category: "Tech",
    type: "Full-time",
    salary: "$95k–118k",
    neighborhood: "Belltown",
    postedAt: "2026-09-19T12:30:00",
    description: "SQL and dashboard work for regional retail clients. Remote-friendly within Washington.",
  },
  {
    id: "j12",
    title: "Front Desk Coordinator",
    company: "Cascade Family Health",
    category: "Office",
    type: "Full-time",
    salary: "$24–27/hr",
    neighborhood: "Northgate",
    postedAt: "2026-09-18T14:50:00",
    description: "Scheduling, insurance verification and patient intake for a six-provider clinic.",
  },
  {
    id: "j13",
    title: "Bakery Assistant",
    company: "Fremont Rise Bakery",
    category: "Hospitality",
    type: "Part-time",
    salary: "$23–26/hr",
    neighborhood: "Ballard",
    postedAt: "2026-09-18T05:15:00",
    description: "Early mornings, shaping and scoring sourdough. No experience needed, willingness to start at 4 a.m. is.",
  },
  {
    id: "j14",
    title: "Personal Trainer",
    company: "Summit Strength Studio",
    category: "Healthcare",
    type: "Contract",
    salary: "$40–60/hr",
    neighborhood: "Queen Anne",
    postedAt: "2026-09-18T09:35:00",
    description: "Build your own client base in a small-group studio. NASM or equivalent certification required.",
  },
];

export const JOB_CATEGORIES = [...new Set(JOB_LISTINGS.map((j) => j.category))].sort();
export const JOB_TYPES = [...new Set(JOB_LISTINGS.map((j) => j.type))];
