export const NEWS_ARTICLES = [
  {
    id: "n1",
    title: "Ballard's Newest Bakery Is Already Selling Out by 9 a.m.",
    category: "Food",
    author: "Priya Nair",
    publishedAt: "2026-09-23T07:45:00",
    photo: "img/news/news-1.webp",
    excerpt: "Fremont Rise Bakery's second location on Ballard Avenue sold through its entire sourdough batch in under two hours on opening day.",
    body: "Fremont Rise Bakery's second location on Ballard Avenue sold through its entire sourdough batch in under two hours on opening day. Owner Dana Kwon says the Ballard shop will add a second oven by October to keep up with demand. Regulars from the original Fremont location have already started making the trip north for the cardamom knots.",
  },
  {
    id: "n2",
    title: "Cal Anderson Park's West Lawn Reopens After Six-Month Drainage Project",
    category: "City Hall",
    author: "Maria Chen",
    publishedAt: "2026-09-23T05:20:00",
    photo: "img/news/news-2.webp",
    excerpt: "Seattle Parks says a new subsurface drainage system should finally keep the field usable through the rainy season.",
    body: "Cal Anderson Park's west lawn reopened to the public this week after a six-month project to fix chronic drainage problems that turned the field to mud every winter. Seattle Parks and Recreation says the new subsurface drainage system should keep the lawn usable through the rainy season for the first time in years. The renovation also added two new benches near the reservoir and repaved a stretch of the path connecting to 11th Avenue. Neighbors who organized a petition over the standing water back in 2024 say they're relieved but want the city to commit to regular maintenance. The splash pad on the east side of the park is unaffected and will run through the end of the month.",
  },
  {
    id: "n3",
    title: "Fremont Oktoberfest Returns This Weekend With a New Beer Garden Layout",
    category: "Community",
    author: "Sofia Reyes",
    publishedAt: "2026-09-22T20:10:00",
    photo: "img/news/news-3.webp",
    excerpt: "Organizers added a second entrance and expanded seating under the Aurora Bridge to ease last year's long lines.",
    body: "Fremont Oktoberfest returns to N 34th Street this weekend with a redesigned beer garden meant to ease last year's long lines at the gate. Organizers added a second entrance off Phinney Avenue and expanded seating under the Aurora Bridge. More than 20 local breweries are pouring this year, including a few new additions from South Park and Georgetown.",
  },
  {
    id: "n4",
    title: "Sound Transit Opens Comment Period on Ballard Link Station Design",
    category: "Transit",
    author: "Tom Whitfield",
    publishedAt: "2026-09-22T09:00:00",
    photo: "img/news/news-4.webp",
    excerpt: "Three station design concepts are up for public comment ahead of an open house at the Ballard branch library.",
    body: "Sound Transit is asking for public input on three design concepts for the future Ballard Link light rail station, with an open house scheduled at the Ballard branch library next month. The proposals differ mainly in where the station entrance would sit relative to 15th Avenue NW and how much surface parking would be removed. Agency planners say construction isn't expected to start until at least 2029, but they want feedback locked in early. Written comments are being accepted online through the end of October.",
  },
  {
    id: "n5",
    title: "First Atmospheric River of the Season Expected This Weekend",
    category: "Weather",
    author: "Jasmine Cole",
    publishedAt: "2026-09-21T16:30:00",
    photo: "img/news/news-5.webp",
    excerpt: "The season's first sustained heavy rain is forecast to move into the region Saturday night.",
    body: "A plume of moisture is forecast to move into the Puget Sound region Saturday night, bringing the season's first sustained heavy rain and gusty wind to the coast and interior lowlands alike. The National Weather Service says isolated areas could see over two inches of rain by Monday morning.",
  },
  {
    id: "n6",
    title: "West Seattle Bridge Inspection Finds No New Cracking, SDOT Says",
    category: "Local",
    author: "Sofia Reyes",
    publishedAt: "2026-09-20T11:00:00",
    photo: "img/news/news-6.webp",
    excerpt: "SDOT's latest inspection found no new cracking since the bridge reopened in 2022.",
    body: "The Seattle Department of Transportation's latest structural inspection of the West Seattle Bridge found no new cracking since repairs were completed in 2022. The bridge is inspected on a rolling schedule as part of the long-term monitoring plan put in place after the closure.",
  },
  {
    id: "n7",
    title: "Occidental Square Packed Before Sounders Match at Lumen Field",
    category: "Sports",
    author: "Marcus Bell",
    publishedAt: "2026-09-19T18:45:00",
    photo: "img/news/news-7.webp",
    excerpt: "Vendors along Occidental Avenue reported some of their busiest foot traffic of the season.",
    body: "Occidental Square was standing room only two hours before kickoff Saturday as Sounders fans gathered in the fan zone before walking down to Lumen Field. Vendors along Occidental Avenue reported some of their busiest foot traffic of the season.",
  },
  {
    id: "n8",
    title: "Wallingford Ramen Shop Adds Seating After a TikTok Video Went Viral",
    category: "Business",
    author: "Derek Alvarez",
    publishedAt: "2026-09-18T08:00:00",
    photo: "img/news/news-8.webp",
    excerpt: "Owner Kevin Tran says weekend wait times had stretched past 90 minutes before the expansion.",
    body: "Fremont Bowl, a small ramen counter on N 45th Street, knocked down a storage wall last week to add eight more seats after a video of its tonkotsu broth passed two million views on TikTok. Owner Kevin Tran says weekend wait times had stretched past 90 minutes. He's now looking at a second location, possibly in Phinney Ridge.",
  },
  {
    id: "n9",
    title: "SPD Hosts Public Safety Q&A in the Chinatown-International District",
    category: "Safety",
    author: "Hana Kobayashi",
    publishedAt: "2026-09-16T14:00:00",
    photo: "img/news/news-9.webp",
    excerpt: "About 40 residents and business owners turned out to a community session at Hing Hay Park.",
    body: "The Seattle Police Department's West Precinct held a community question-and-answer session at Hing Hay Park Tuesday evening, fielding questions about foot patrol frequency and lighting along South Jackson Street. About 40 residents and business owners attended.",
  },
  {
    id: "n10",
    title: "Overlook Walk at the Waterfront Park Opens to the Public",
    category: "City Hall",
    author: "Maria Chen",
    publishedAt: "2026-09-14T10:00:00",
    photo: "img/news/news-10.webp",
    excerpt: "The pedestrian bridge connecting Pike Place Market to the waterfront park opened this week after years of construction.",
    body: "The Overlook Walk, the pedestrian bridge connecting Pike Place Market to the new waterfront park, opened to the public this week after years of construction tied to the Alaskan Way Viaduct replacement. The terraced walkway includes a new play area, a small amphitheater, and unobstructed views of Elliott Bay from above the seawall. City officials held a short ribbon-cutting Tuesday morning, though the space had already drawn crowds over the weekend before the official opening. The final phase of landscaping along the promenade is expected to wrap by early next year.",
  },
  {
    id: "n11",
    title: "Ballard Farmers Market Vendors Call It the Best Tomato Season in Years",
    category: "Community",
    author: "Priya Nair",
    publishedAt: "2026-09-11T09:30:00",
    photo: "img/news/news-11.webp",
    excerpt: "A warm, dry August produced some of the best heirloom tomatoes local growers have seen in a decade.",
    body: "Vendors at the Sunday Ballard Farmers Market say this year's warm, dry stretch in August produced some of the best heirloom tomatoes they've seen in a decade. Several stalls sold out by 11 a.m. two weekends in a row.",
  },
  {
    id: "n12",
    title: "Georgetown's Art Attack Brings Pop-Up Galleries to Airport Way",
    category: "Community",
    author: "Marcus Bell",
    publishedAt: "2026-09-08T15:00:00",
    photo: "img/news/news-12.webp",
    excerpt: "More than a dozen studios along Airport Way South will open for the free self-guided walk Saturday night.",
    body: "Georgetown's monthly Art Attack returns Saturday night, with more than a dozen studios and pop-up galleries along Airport Way South opening their doors for the free self-guided walk. Several spaces are showing new work for the first time since summer.",
  },
  {
    id: "n13",
    title: "Pike Place Market Extends Evening Hours Through the End of October",
    category: "Community",
    author: "Sofia Reyes",
    publishedAt: "2026-09-07T11:00:00",
    photo: "img/hero/pike-place.webp",
    excerpt: "Stalls on the main arcade will stay open until 7 p.m. on Fridays and Saturdays for the rest of the fall season.",
    body: "The Pike Place Market Preservation and Development Authority is extending evening hours through the end of October, keeping stalls on the main arcade open until 7 p.m. on Fridays and Saturdays. The trial ran for three weekends in August and brought enough foot traffic that a majority of the farm and craft vendors asked to continue it. Market staff say the later hours mainly help commuters who cannot get down the hill before the usual 5 p.m. close.",
  },
  {
    id: "n14",
    title: "Waterfront Ferry Terminal Opens a Second Passenger Gangway",
    category: "Transit",
    author: "Tom Whitfield",
    publishedAt: "2026-09-05T08:30:00",
    photo: "img/hero/waterfront.webp",
    excerpt: "Washington State Ferries says the second walkway at Colman Dock should cut boarding times on the Bainbridge run.",
    body: "Washington State Ferries has opened a second passenger gangway at Colman Dock, the last major piece of a terminal rebuild that has been under way in phases since 2017. Crews expect boarding on the Bainbridge Island run to move noticeably faster during the evening peak, when a single walkway had been handling well over a thousand walk-on riders per sailing. The agency is keeping the old ramp in service as a backup.",
  },
  {
    id: "n15",
    title: "Downtown Office Vacancy Falls for a Third Straight Quarter",
    category: "Business",
    author: "Derek Alvarez",
    publishedAt: "2026-09-03T16:00:00",
    photo: "img/hero/downtown.webp",
    excerpt: "Brokers credit smaller leases near the retail core rather than any single large tenant returning to the market.",
    body: "Downtown office vacancy dropped for a third consecutive quarter, according to figures circulated by several commercial brokerages this week. The gains came from a long list of leases under 10,000 square feet clustered near the retail core, not from any single large tenant returning to the market. Buildings on the north end of the central business district are still lagging, and a few older towers remain more than half empty.",
  },
  {
    id: "n16",
    title: "Space Needle Observation Deck Closes for Two Nights of Glass Work",
    category: "City Hall",
    author: "Maria Chen",
    publishedAt: "2026-09-01T09:15:00",
    photo: "img/hero/space-needle.webp",
    excerpt: "Crews will replace two panels on the upper deck overnight, with the restaurant level staying open on both evenings.",
    body: "The Space Needle will close its upper observation deck for two nights this month while crews replace a pair of glass panels installed during the 2018 renovation. Work is scheduled overnight to keep daytime visits unaffected, and the rotating restaurant level stays open on both evenings. Tickets bought for the affected hours are being refunded automatically.",
  },
  {
    id: "n17",
    title: "Paradise Road Reopens After a Late-Summer Rockfall at Mount Rainier",
    category: "Local",
    author: "Jasmine Cole",
    publishedAt: "2026-08-30T10:20:00",
    photo: "img/hero/mount-rainier.webp",
    excerpt: "Crews cleared the slide and rebuilt a shoulder that had washed out below Narada Falls.",
    body: "The road to Paradise reopened this week after crews cleared a rockfall that had closed the upper stretch for eleven days. Park staff also rebuilt a shoulder below Narada Falls that washed out during the same storm. Rangers are asking drivers to expect single-lane control at two points through the end of the season.",
  },
  {
    id: "n18",
    title: "Capitol Hill Coffee Roaster Opens a Second Bar on 12th Avenue",
    category: "Food",
    author: "Priya Nair",
    publishedAt: "2026-08-28T08:40:00",
    photo: "img/business/biz-1.webp",
    excerpt: "The new room seats thirty and keeps the roastery's single-origin menu, minus the pastry case.",
    body: "Bright Hill Coffee has opened a second bar on 12th Avenue, two blocks from the roastery it has run since 2019. The new room seats thirty and carries the same single-origin menu, though owner Nell Vasquez says there will be no pastry case at this location. Morning hours start at six on weekdays.",
  },
  {
    id: "n19",
    title: "Pioneer Square Bookstore Buys the Storefront Next Door",
    category: "Business",
    author: "Derek Alvarez",
    publishedAt: "2026-08-26T13:05:00",
    photo: "img/business/biz-2.webp",
    excerpt: "The expansion doubles the shop's floor space and adds a room for readings and small events.",
    body: "Occidental Books has bought the storefront next door, doubling its floor space after fourteen years in the same building. The new room will hold the used-book stock and a small stage for readings. The owners say the purchase was possible only because the landlord offered them the space before listing it.",
  },
  {
    id: "n20",
    title: "Rainier Beach Hardware Store Marks Fifty Years Under One Family",
    category: "Community",
    author: "Hana Kobayashi",
    publishedAt: "2026-08-24T09:30:00",
    photo: "img/business/biz-3.webp",
    excerpt: "Three generations have run the counter on Rainier Avenue South since the shop opened in 1976.",
    body: "The hardware store on Rainier Avenue South turned fifty this month, still run by the family that opened it in 1976. Three generations have worked the counter, and the current owner started stocking shelves there at fourteen. A block party on Saturday drew several hundred neighbors.",
  },
  {
    id: "n21",
    title: "Beacon Hill Night Market Adds a Second Weekend in September",
    category: "Community",
    author: "Sofia Reyes",
    publishedAt: "2026-08-22T18:15:00",
    photo: "img/business/biz-4.webp",
    excerpt: "Organizers say the July market drew twice the expected crowd, so a second date has been added.",
    body: "The Beacon Hill night market will run a second weekend in September after the July edition drew roughly twice the crowd organizers had planned for. Forty vendors are confirmed, up from twenty-six. The market keeps its spot in the lot behind the community center and runs from five until ten.",
  },
  {
    id: "n22",
    title: "Greenwood Hardware Co-op Votes to Extend Sunday Hours",
    category: "Business",
    author: "Marcus Bell",
    publishedAt: "2026-08-20T11:45:00",
    photo: "img/business/biz-5.webp",
    excerpt: "Members approved the change after a survey found Sunday afternoon was the busiest blocked hour.",
    body: "Members of the Greenwood hardware co-op voted to keep the store open until six on Sundays, two hours later than the current close. A member survey found Sunday afternoon was the single busiest hour customers could not shop. The change takes effect at the start of next month.",
  },
  {
    id: "n23",
    title: "Columbia City Library Reopens Its Basement Meeting Room",
    category: "City Hall",
    author: "Maria Chen",
    publishedAt: "2026-08-18T14:00:00",
    photo: "img/business/biz-6.webp",
    excerpt: "The room had been closed since a 2024 pipe failure and is bookable again for community groups.",
    body: "The basement meeting room at the Columbia City branch is bookable again after a pipe failure closed it in the spring of 2024. The library replaced the flooring and added a second exit to meet current code. Community groups can reserve the room online at no charge, as before.",
  },
  {
    id: "n24",
    title: "South Lake Union Food Hall Fills Its Last Two Stalls",
    category: "Food",
    author: "Priya Nair",
    publishedAt: "2026-08-16T12:30:00",
    photo: "img/business/biz-7.webp",
    excerpt: "A Filipino bakery and a soup counter take the two spaces that stood empty since the hall opened.",
    body: "The food hall on Westlake Avenue has leased its final two stalls to a Filipino bakery and a soup counter, filling a floor plan that had two dark corners since it opened in March. Both operators are first-time brick-and-mortar tenants who had been running farmers market stands. They expect to open by the middle of next month.",
  },
  {
    id: "n25",
    title: "White Center Grocers Form a Joint Delivery Route",
    category: "Business",
    author: "Derek Alvarez",
    publishedAt: "2026-08-14T10:10:00",
    photo: "img/business/biz-8.webp",
    excerpt: "Six independent stores are splitting one van three days a week to reach customers south of the line.",
    body: "Six independent grocers in White Center have pooled money for a shared delivery van running three days a week. Each store pays by the stop rather than by the hour, which the organizers say is the only structure small enough shops could agree on. The route covers the neighborhoods immediately south of the city line.",
  },
  {
    id: "n26",
    title: "Phinney Ridge Hardware Store Starts a Neighborhood Tool Library",
    category: "Community",
    author: "Hana Kobayashi",
    publishedAt: "2026-08-12T15:50:00",
    photo: "img/business/biz-9.webp",
    excerpt: "Tile saws, augers and pressure washers go out for three days on a deposit instead of a rental fee.",
    body: "A hardware store on Greenwood Avenue North has set aside a back room as a lending library for tools most households need once a year. Tile saws, augers and pressure washers go out for three days on a refundable deposit rather than a rental fee. The owner says the shelf paid for itself in goodwill within a month.",
  },
  {
    id: "n27",
    title: "West Seattle Junction Brewery Reopens After a Summer Remodel",
    category: "Food",
    author: "Sofia Reyes",
    publishedAt: "2026-08-10T17:20:00",
    photo: "img/business/biz-10.webp",
    excerpt: "The taproom gained a second bar and lost eight seats, a trade the owners say the kitchen needed.",
    body: "The brewery at the West Seattle Junction is pouring again after eight weeks of construction. The taproom gained a second bar along the north wall and lost eight seats to a larger kitchen line. The brewing side never stopped, so the tap list is unchanged.",
  },
  {
    id: "n28",
    title: "Lake City Way Storefronts Get New Awnings From a City Grant",
    category: "Local",
    author: "Marcus Bell",
    publishedAt: "2026-08-08T09:00:00",
    photo: "img/business/biz-11.webp",
    excerpt: "Eleven businesses split a facade improvement grant that had gone unclaimed for two years running.",
    body: "Eleven businesses along a four-block stretch of Lake City Way have replaced their awnings and signs using a facade improvement grant that had gone unclaimed two years running. The office administering it says the application was rewritten this spring after shop owners said the old one took a weekend to fill out.",
  },
];

// Подборка редакции для виджета Top News на news.html: «самое главное», а не
// самое свежее и не самое читаемое — поэтому это ручной список id, а не срез
// массива и не сортировка. Порядок здесь и есть порядок в виджете.
export const TOP_NEWS_IDS = ["n5", "n6", "n10", "n2", "n15", "n17"];
