// Вопросы и ответы раздела Q&A. Отвечает «редакция» — на демо это читается
// как редакционная колонка, а не как живой форум, и ничего не обещает.

export const QA_ITEMS = [
  { id: "q1", topic: "Getting Around", question: "Do I need a car to live in Seattle?", answer: "In the neighbourhoods along the light rail line — Capitol Hill, Columbia City, Downtown, Northgate — plenty of people manage without one. Further out, especially west of the canal, buses thin out in the evening and a car starts to matter.", askedBy: "Dana R.", askedAt: "2026-09-22T10:00:00" },
  { id: "q2", topic: "Getting Around", question: "What does an ORCA card cover?", answer: "Buses, light rail, the streetcar, the water taxi and Sounder trains, all on one card. You tap on and, on rail, tap off as well — forgetting the tap-off is the usual reason for an unexpected charge.", askedBy: "Marcus T.", askedAt: "2026-09-21T14:30:00" },
  { id: "q3", topic: "Getting Around", question: "Is the ferry worth taking as a visitor?", answer: "The Bainbridge crossing is thirty-five minutes each way and gives you the skyline from the water for the price of a walk-on ticket. Walk on rather than drive: the vehicle queue on a summer weekend can be two sailings deep.", askedBy: "Priya S.", askedAt: "2026-09-20T09:15:00" },
  { id: "q4", topic: "Housing", question: "How far ahead should I start looking for a rental?", answer: "Four to six weeks. Listings here move quickly and most landlords want a start date within a month, so looking three months out mostly turns up places that will be gone by the time you need them.", askedBy: "Elena K.", askedAt: "2026-09-22T08:45:00" },
  { id: "q5", topic: "Housing", question: "What is a standard deposit?", answer: "Usually one month of rent, sometimes with a separate non-refundable move-in fee. State law caps what can be charged and requires a written checklist of the condition of the property before you move in. Ask for it if it is not offered.", askedBy: "Tom W.", askedAt: "2026-09-19T16:20:00" },
  { id: "q6", topic: "Housing", question: "Which neighbourhoods are quietest?", answer: "Wallingford, Green Lake and the residential streets of Queen Anne are the usual answers. Capitol Hill and Ballard Avenue are the opposite, lively until late, which is the point for some people.", askedBy: "Sofia R.", askedAt: "2026-09-18T11:05:00" },
  { id: "q7", topic: "City Services", question: "When is rubbish and recycling collected?", answer: "Weekly, on a day that depends on your address, with food and yard waste on the same round. The city publishes a lookup by street number, and collection shifts a day later during the week of a public holiday.", askedBy: "James L.", askedAt: "2026-09-21T07:50:00" },
  { id: "q8", topic: "City Services", question: "How do I report a pothole or a broken streetlight?", answer: "Through the service request line of the city or its app. Streetlights are usually the fastest, because they are logged against a pole number, and the number is printed on the pole itself.", askedBy: "Nina B.", askedAt: "2026-09-20T13:40:00" },
  { id: "q9", topic: "City Services", question: "Where can I take things that do not go in the bin?", answer: "The two transfer stations take household hazardous waste, electronics and bulky items. Paint and batteries have their own drop-off points, several of them at hardware shops rather than city sites.", askedBy: "Oliver M.", askedAt: "2026-09-18T15:10:00" },
  { id: "q10", topic: "Food & Drink", question: "Is Pike Place Market worth it, or is it a tourist trap?", answer: "Both. Go before nine on a weekday and it is a working market with the fishmongers and growers doing actual trade. Go at noon on a Saturday and you will spend the visit in a queue.", askedBy: "Hannah G.", askedAt: "2026-09-22T12:15:00" },
  { id: "q11", topic: "Food & Drink", question: "Do restaurants here take cash?", answer: "Many no longer do. Card or phone is the safe assumption, and service charges are increasingly added to the bill instead of being left to the customer. Check the bottom of the receipt before tipping again.", askedBy: "Victor A.", askedAt: "2026-09-19T19:00:00" },
  { id: "q12", topic: "Newcomers", question: "How bad is the rain, really?", answer: "It rains often and lightly rather than heavily. The number that surprises people is the darkness, not the rainfall: December afternoons end around half past four. A waterproof jacket beats an umbrella for most of it.", askedBy: "Amara O.", askedAt: "2026-09-21T10:25:00" },
  { id: "q13", topic: "Newcomers", question: "What is the Seattle Freeze?", answer: "The local name for the gap between being friendly and making friends. People are pleasant and slow to commit to plans. The usual advice is to join something with a fixed schedule, a class, a league or a volunteer shift, rather than wait for invitations.", askedBy: "Chris D.", askedAt: "2026-09-20T17:35:00" },
  { id: "q14", topic: "Newcomers", question: "Is there a state income tax?", answer: "No. Washington has no personal income tax, and makes it up with a high sales tax and property taxes. Budget for the sales tax on top of every listed price, because it is not included on the shelf label.", askedBy: "Riya P.", askedAt: "2026-09-18T09:30:00" },
  { id: "q15", topic: "Business", question: "What do I need to open a small shop here?", answer: "A state business licence, a city licence on top of it, and registration for sales tax. Food service adds a county health permit and an inspection before you can open the doors.", askedBy: "Grace H.", askedAt: "2026-09-22T09:10:00" },
  { id: "q16", topic: "Business", question: "Where do local businesses advertise?", answer: "Neighbourhood blogs, the free weeklies, and city portals like this one. For a small shop, a listing with a phone number where people already look usually beats a campaign somewhere they do not.", askedBy: "Daniel F.", askedAt: "2026-09-19T11:55:00" },
];

export const QA_TOPICS = [...new Set(QA_ITEMS.map((q) => q.topic))];
