// Объекты раздела Real Estate. price — число, чтобы по нему можно было
// фильтровать и сортировать; priceLabel — то, что видит человек. У аренды
// цена месячная, поэтому фильтр максимальной цены строится отдельно для
// продажи и для аренды.
// Фото делятся с пулами img/news/ и img/hero/ — своих снимков недвижимости
// в проекте нет, а скачивать чужие нельзя.

export const PROPERTIES = [
  { id: "p1", title: "Craftsman bungalow with a finished basement", deal: "For Sale", price: 845000, priceLabel: "$845,000", beds: 3, baths: 2, sqft: 1840, neighborhood: "Ballard", listedAt: "2026-09-23T09:00:00", photo: "img/news/news-4.jpg", description: "Original 1924 woodwork, a rebuilt kitchen and a detached garage on a quiet block two streets off Market." },
  { id: "p2", title: "Two-bedroom apartment above the canal", deal: "For Rent", price: 2650, priceLabel: "$2,650/mo", beds: 2, baths: 1, sqft: 940, neighborhood: "Fremont", listedAt: "2026-09-23T07:30:00", photo: "img/news/news-6.jpg", description: "Corner unit with south light, in-unit laundry and one parking space. Water and rubbish included." },
  { id: "p3", title: "Top-floor condo with Sound views", deal: "For Sale", price: 1125000, priceLabel: "$1,125,000", beds: 2, baths: 2, sqft: 1290, neighborhood: "Belltown", listedAt: "2026-09-22T14:10:00", photo: "img/hero/waterfront.jpg", description: "Floor-to-ceiling glass on the west side, concrete building, doorman and a rooftop terrace." },
  { id: "p4", title: "Studio a block from the light rail", deal: "For Rent", price: 1595, priceLabel: "$1,595/mo", beds: 0, baths: 1, sqft: 480, neighborhood: "Capitol Hill", listedAt: "2026-09-22T11:45:00", photo: "img/news/news-9.jpg", description: "Small but well laid out, with a proper kitchen and a shared roof deck. Six-month terms available." },
  { id: "p5", title: "Four-bedroom family house near the lake", deal: "For Sale", price: 1390000, priceLabel: "$1,390,000", beds: 4, baths: 3, sqft: 2620, neighborhood: "Green Lake", listedAt: "2026-09-22T08:20:00", photo: "img/news/news-5.jpg", description: "Extended in 2019, level garden, and the park path at the end of the street." },
  { id: "p6", title: "One-bedroom in a restored brick building", deal: "For Rent", price: 2150, priceLabel: "$2,150/mo", beds: 1, baths: 1, sqft: 720, neighborhood: "Pioneer Square", listedAt: "2026-09-21T16:00:00", photo: "img/news/news-3.jpg", description: "Exposed brick, high ceilings and original windows. Building has a lift and secure entry." },
  { id: "p7", title: "Townhouse with a rooftop deck", deal: "For Sale", price: 925000, priceLabel: "$925,000", beds: 3, baths: 3, sqft: 1710, neighborhood: "Columbia City", listedAt: "2026-09-21T10:30:00", photo: "img/news/news-10.jpg", description: "Built 2021, heat pump, two parking spaces and a deck with a clear view of Rainier." },
  { id: "p8", title: "Ground-floor flat with a private garden", deal: "For Rent", price: 2950, priceLabel: "$2,950/mo", beds: 2, baths: 2, sqft: 1120, neighborhood: "Wallingford", listedAt: "2026-09-20T15:15:00", photo: "img/news/news-2.jpg", description: "Rare fenced garden, dog friendly, and a garage space included in the rent." },
  { id: "p9", title: "Mid-century house on a corner lot", deal: "For Sale", price: 1075000, priceLabel: "$1,075,000", beds: 3, baths: 2, sqft: 1960, neighborhood: "Queen Anne", listedAt: "2026-09-20T12:00:00", photo: "img/hero/space-needle.jpg", description: "Single level, big windows, and the original 1958 fireplace. Needs a kitchen but the bones are sound." },
  { id: "p10", title: "Loft in a converted warehouse", deal: "For Rent", price: 2400, priceLabel: "$2,400/mo", beds: 1, baths: 1, sqft: 980, neighborhood: "Georgetown", listedAt: "2026-09-19T17:40:00", photo: "img/news/news-12.jpg", description: "Open plan with a mezzanine bedroom, freight lift and a shared workshop in the basement." },
  { id: "p11", title: "Duplex, both halves vacant", deal: "For Sale", price: 1480000, priceLabel: "$1,480,000", beds: 6, baths: 4, sqft: 3200, neighborhood: "Ballard", listedAt: "2026-09-19T09:50:00", photo: "img/news/news-1.jpg", description: "Two three-bedroom units, separately metered, roof replaced last year. Live in one, let the other." },
  { id: "p12", title: "Compact two-bed with skyline views", deal: "For Rent", price: 3200, priceLabel: "$3,200/mo", beds: 2, baths: 2, sqft: 1050, neighborhood: "Downtown", listedAt: "2026-09-18T13:25:00", photo: "img/hero/downtown.jpg", description: "Twenty-second floor, floor heating, gym and co-working space in the building." },
  { id: "p13", title: "Cottage with a workshop", deal: "For Sale", price: 685000, priceLabel: "$685,000", beds: 2, baths: 1, sqft: 1150, neighborhood: "Georgetown", listedAt: "2026-09-18T10:05:00", photo: "img/news/news-11.jpg", description: "Small house, big garage. Zoned to allow a second dwelling at the back of the plot." },
  { id: "p14", title: "Three-bed rental near the station", deal: "For Rent", price: 3450, priceLabel: "$3,450/mo", beds: 3, baths: 2, sqft: 1480, neighborhood: "Columbia City", listedAt: "2026-09-18T08:00:00", photo: "img/news/news-7.jpg", description: "Recently repainted, new appliances, and a five-minute walk to the platform." },
];

export const PROPERTY_DEALS = ["For Sale", "For Rent"];
export const PROPERTY_NEIGHBORHOODS = [...new Set(PROPERTIES.map((p) => p.neighborhood))].sort();
