/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    'news-categories': NewsCategory;
    businesses: Business;
    'business-categories': BusinessCategory;
    packages: Package;
    promotions: Promotion;
    products: Product;
    'car-listings': CarListing;
    'car-makes': CarMake;
    jobs: Job;
    'job-categories': JobCategory;
    events: Event;
    'event-categories': EventCategory;
    contests: Contest;
    submissions: Submission;
    'ad-slots': AdSlot;
    banners: Banner;
    'banner-stats': BannerStat;
    pages: Page;
    media: Media;
    documents: Document;
    users: User;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    'news-categories': NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    'business-categories': BusinessCategoriesSelect<false> | BusinessCategoriesSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'car-listings': CarListingsSelect<false> | CarListingsSelect<true>;
    'car-makes': CarMakesSelect<false> | CarMakesSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-categories': JobCategoriesSelect<false> | JobCategoriesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-categories': EventCategoriesSelect<false> | EventCategoriesSelect<true>;
    contests: ContestsSelect<false> | ContestsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'ad-slots': AdSlotsSelect<false> | AdSlotsSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    'banner-stats': BannerStatsSelect<false> | BannerStatsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * One or two sentences. Shown in the feed and used as the default search description.
   */
  excerpt: string;
  cover?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?: (number | Media)[] | null;
  /**
   * Optional: where the story came from — a name or a link.
   */
  source?: string | null;
  /**
   * Part of the page address. Leave empty to generate it from the title.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  publishedAt: string;
  category: number | NewsCategory;
  /**
   * Shown in the Top news block.
   */
  isTop?: boolean | null;
  author?: string | null;
  tags?: string[] | null;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  /**
   * Old addresses of this page. They redirect here automatically.
   */
  slugHistory?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the picture shows, for screen readers and search engines.
   */
  alt: string;
  credit?: string | null;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories".
 */
export interface NewsCategory {
  id: number;
  name: string;
  /**
   * Part of the page address. Leave empty to generate it from the title.
   */
  slug?: string | null;
  description?: string | null;
  order?: number | null;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: number;
  name: string;
  /**
   * How many are allowed depends on the package.
   */
  categories: (number | BusinessCategory)[];
  logo?: (number | null) | Media;
  /**
   * The picture in the directory list.
   */
  cover?: (number | null) | Media;
  /**
   * One or two sentences for the directory list and search engines.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Street address in Seattle. Coordinates are filled in from it automatically.
   */
  address?: string | null;
  lat?: number | null;
  lng?: number | null;
  /**
   * The address could not be placed on the map automatically.
   */
  geocodeNote?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  hours?:
    | {
        /**
         * e.g. Mon–Fri
         */
        days: string;
        /**
         * e.g. 7:00 AM – 6:00 PM, or Closed
         */
        time: string;
        id?: string | null;
      }[]
    | null;
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    x?: string | null;
    yelp?: string | null;
  };
  /**
   * How many are allowed depends on the package.
   */
  gallery?: (number | Media)[] | null;
  priceLists?: (number | Document)[] | null;
  certificates?: (number | Document)[] | null;
  package?: (number | null) | Package;
  /**
   * After this date the business drops to the basic listing automatically.
   */
  packageExpiresAt?: string | null;
  /**
   * Manual ordering inside the same package: higher shows first.
   */
  priority?: number | null;
  /**
   * yourname → yourname.<site domain>. Luxury and Premium only.
   */
  subdomain?: string | null;
  /**
   * Used only with a package that includes a branded page.
   */
  branding?: {
    headerImage?: (number | null) | Media;
    brandColor?: string | null;
  };
  /**
   * Part of the page address. Leave empty to generate it from the title.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  viewsCount?: number | null;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  /**
   * Old addresses of this page. They redirect here automatically.
   */
  slugHistory?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-categories".
 */
export interface BusinessCategory {
  id: number;
  name: string;
  /**
   * Part of the page address. Leave empty to generate it from the title.
   */
  slug?: string | null;
  section: 'directory' | 'shopping' | 'leisure';
  /**
   * Leave empty for a top-level category.
   */
  parent?: (number | null) | BusinessCategory;
  icon?: (number | null) | Media;
  description?: string | null;
  order?: number | null;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Shown as the link text, e.g. "Spring menu 2026"
   */
  title: string;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  name: string;
  /**
   * Higher = more expensive tier. Premium ranks above Luxury in the directory.
   */
  order: number;
  /**
   * 0 = "Contact us"
   */
  priceMonthly: number;
  /**
   * 0 = "Contact us"
   */
  priceYearly: number;
  currency: 'USD';
  maxCategories: number;
  maxPhotos: number;
  /**
   * Car listings and job postings together
   */
  maxListings: number;
  maxProducts: number;
  mapPlacement?: boolean | null;
  promotions?: boolean | null;
  priceLists?: boolean | null;
  subdomain?: boolean | null;
  priorityPlacement?: boolean | null;
  categoryBannerFirstMonth?: boolean | null;
  brandedPage?: boolean | null;
  /**
   * Bullet points for the packages table on /advertise.
   */
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  business: number | Business;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  validFrom: string;
  validUntil: string;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  business: number | Business;
  name: string;
  /**
   * USD. Empty = "Ask for price".
   */
  price?: number | null;
  image?: (number | null) | Media;
  description?: string | null;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-listings".
 */
export interface CarListing {
  id: number;
  /**
   * Leave empty: it is built from year, make and model.
   */
  title?: string | null;
  make: number | CarMake;
  model: string;
  year: number;
  /**
   * USD
   */
  price: number;
  /**
   * miles
   */
  mileage: number;
  /**
   * e.g. 2.5L I4 Hybrid
   */
  engine?: string | null;
  transmission: 'Automatic' | 'CVT Automatic' | 'Manual';
  fuelType: 'Gasoline' | 'Diesel' | 'Hybrid' | 'Plug-in Hybrid' | 'Electric';
  drivetrain?: ('FWD' | 'RWD' | 'AWD' | '4WD') | null;
  bodyType: 'sedan' | 'suv' | 'truck' | 'hatchback' | 'coupe' | 'convertible' | 'wagon' | 'van';
  exteriorColor?: string | null;
  vin?: string | null;
  description?: string | null;
  /**
   * The first photo is the cover.
   */
  photos?: (number | Media)[] | null;
  sellerName: string;
  sellerPhone: string;
  /**
   * If a dealership sells it. Counts towards the dealer package’s listing limit.
   */
  dealer?: (number | null) | Business;
  /**
   * Part of the page address. Leave empty to generate it.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  isFeatured?: boolean | null;
  /**
   * "Bump" a listing to the top of the catalog by setting this to now.
   */
  bumpedAt?: string | null;
  expiresAt?: string | null;
  /**
   * User submissions arrive in stage 3.
   */
  source: 'admin' | 'user';
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  /**
   * Old addresses of this page. They redirect here automatically.
   */
  slugHistory?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-makes".
 */
export interface CarMake {
  id: number;
  name: string;
  /**
   * Type a model and press Enter.
   */
  models?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * A business from the directory…
   */
  business?: (number | null) | Business;
  /**
   * …or just the company name.
   */
  companyName?: string | null;
  category: number | JobCategory;
  employmentType: 'full-time' | 'part-time' | 'contract' | 'temporary';
  workMode?: ('on-site' | 'hybrid' | 'remote') | null;
  salaryMin?: number | null;
  salaryMax?: number | null;
  salaryPeriod?: ('hour' | 'year') | null;
  /**
   * Neighbourhood or address, e.g. Capitol Hill
   */
  location?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Two lines for the job board list.
   */
  summary?: string | null;
  /**
   * Email, phone or link — shown on the job page.
   */
  howToApply: string;
  openTo?: ('noExperience' | 'students' | 'accessible' | 'fiftyPlus')[] | null;
  perks?: string[] | null;
  languages?: string[] | null;
  isUrgent?: boolean | null;
  isFeatured?: boolean | null;
  /**
   * Part of the page address. Leave empty to generate it.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  expiresAt?: string | null;
  source?: ('admin' | 'user') | null;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  /**
   * Old addresses of this page. They redirect here automatically.
   */
  slugHistory?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-categories".
 */
export interface JobCategory {
  id: number;
  name: string;
  /**
   * Part of the page address. Leave empty to generate it from the title.
   */
  slug?: string | null;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  startAt: string;
  endAt?: string | null;
  category: number | EventCategory;
  venueName: string;
  address?: string | null;
  lat?: number | null;
  lng?: number | null;
  geocodeNote?: string | null;
  isFree?: boolean | null;
  /**
   * e.g. $35, or $20–60
   */
  price?: string | null;
  ticketUrl?: string | null;
  image?: (number | null) | Media;
  /**
   * Two lines for the event card.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Part of the page address. Leave empty to generate it.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  /**
   * Old addresses of this page. They redirect here automatically.
   */
  slugHistory?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-categories".
 */
export interface EventCategory {
  id: number;
  name: string;
  /**
   * Part of the page address. Leave empty to generate it from the title.
   */
  slug?: string | null;
  order?: number | null;
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contests".
 */
export interface Contest {
  id: number;
  title: string;
  description?: string | null;
  rules?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startAt?: string | null;
  endAt?: string | null;
  entries?:
    | {
        image: number | Media;
        title: string;
        /**
         * First name only — no surname.
         */
        participantFirstName: string;
        participantAge: number;
        parentConsent: boolean;
        id?: string | null;
      }[]
    | null;
  /**
   * Part of the page address. Leave empty to generate it from the title.
   */
  slug?: string | null;
  status: 'upcoming' | 'active' | 'finished';
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  /**
   * Old addresses of this page. They redirect here automatically.
   */
  slugHistory?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  type: 'news_tip' | 'business_registration' | 'ad_inquiry';
  status: 'new' | 'in_progress' | 'done' | 'rejected';
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  message?: string | null;
  businessName?: string | null;
  category?: (number | null) | BusinessCategory;
  desiredPackage?: (number | null) | Package;
  /**
   * Ad placement the visitor asked about
   */
  desiredSlot?: string | null;
  photos?: (number | Media)[] | null;
  location?: string | null;
  /**
   * Only the team sees this.
   */
  internalNotes?: string | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Places on the site where banners appear. The code must match the slot in the page code — do not rename.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-slots".
 */
export interface AdSlot {
  id: number;
  /**
   * e.g. HOME_TOP
   */
  code: string;
  /**
   * Human name for /advertise, e.g. "Home — top banner"
   */
  name?: string | null;
  page:
    | 'home'
    | 'news'
    | 'directory'
    | 'shopping'
    | 'leisure'
    | 'business'
    | 'events'
    | 'cars'
    | 'jobs'
    | 'weather'
    | 'all';
  position: 'leaderboard' | 'sidebar' | 'in-feed';
  desktopSize: '970x250' | '728x90' | '300x250' | '300x600' | '320x100';
  /**
   * Empty = the slot is hidden on phones
   */
  mobileSize?: ('970x250' | '728x90' | '300x250' | '300x600' | '320x100') | null;
  /**
   * USD per week. 0 = "Contact us"
   */
  weeklyPrice: number;
  sortOrder?: number | null;
  /**
   * Off = the slot shows nothing and is not offered on /advertise
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  advertiser: string;
  /**
   * Where a click leads, e.g. https://example.com — counted, then redirected.
   */
  linkUrl: string;
  slots: (number | AdSlot)[];
  /**
   * Exactly the slot's desktop size (±2px)
   */
  imageDesktop: number | Media;
  /**
   * For slots shown on phones: the slot's mobile size
   */
  imageMobile?: (number | null) | Media;
  startAt: string;
  endAt: string;
  status: 'draft' | 'published';
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Daily impressions and clicks, written by the site. Read-only — see the report on a banner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner-stats".
 */
export interface BannerStat {
  id: number;
  banner: number | Banner;
  /**
   * YYYY-MM-DD, Seattle time
   */
  date: string;
  impressions: number;
  clicks: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  intro?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            text: string;
            buttonLabel: string;
            buttonUrl: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  /**
   * Part of the page address. Leave empty to generate it from the title.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  /**
   * Demo content. Removed in one go by `pnpm purge-demo` before launch.
   */
  isDemo?: boolean | null;
  /**
   * Old addresses of this page. They redirect here automatically.
   */
  slugHistory?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admin: everything. Editor: news, events, contest, news tips. Sales: businesses, packages, banners, placement requests.
   */
  roles: ('admin' | 'editor' | 'sales')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'news';
        value: number | News;
      }
    | {
        relationTo: 'businesses';
        value: number | Business;
      }
    | {
        relationTo: 'car-listings';
        value: number | CarListing;
      }
    | {
        relationTo: 'jobs';
        value: number | Job;
      }
    | {
        relationTo: 'events';
        value: number | Event;
      };
  url?: string | null;
  excerpt?: string | null;
  kind?: string | null;
  keywords?: string | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'news-categories';
        value: number | NewsCategory;
      } | null)
    | ({
        relationTo: 'businesses';
        value: number | Business;
      } | null)
    | ({
        relationTo: 'business-categories';
        value: number | BusinessCategory;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'car-listings';
        value: number | CarListing;
      } | null)
    | ({
        relationTo: 'car-makes';
        value: number | CarMake;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'job-categories';
        value: number | JobCategory;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-categories';
        value: number | EventCategory;
      } | null)
    | ({
        relationTo: 'contests';
        value: number | Contest;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'ad-slots';
        value: number | AdSlot;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'banner-stats';
        value: number | BannerStat;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  gallery?: T;
  source?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  category?: T;
  isTop?: T;
  author?: T;
  tags?: T;
  isDemo?: T;
  slugHistory?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  name?: T;
  categories?: T;
  logo?: T;
  cover?: T;
  summary?: T;
  description?: T;
  address?: T;
  lat?: T;
  lng?: T;
  geocodeNote?: T;
  phone?: T;
  email?: T;
  website?: T;
  hours?:
    | T
    | {
        days?: T;
        time?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        x?: T;
        yelp?: T;
      };
  gallery?: T;
  priceLists?: T;
  certificates?: T;
  package?: T;
  packageExpiresAt?: T;
  priority?: T;
  subdomain?: T;
  branding?:
    | T
    | {
        headerImage?: T;
        brandColor?: T;
      };
  slug?: T;
  status?: T;
  viewsCount?: T;
  isDemo?: T;
  slugHistory?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-categories_select".
 */
export interface BusinessCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  section?: T;
  parent?: T;
  icon?: T;
  description?: T;
  order?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  priceMonthly?: T;
  priceYearly?: T;
  currency?: T;
  maxCategories?: T;
  maxPhotos?: T;
  maxListings?: T;
  maxProducts?: T;
  mapPlacement?: T;
  promotions?: T;
  priceLists?: T;
  subdomain?: T;
  priorityPlacement?: T;
  categoryBannerFirstMonth?: T;
  brandedPage?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  business?: T;
  title?: T;
  description?: T;
  image?: T;
  validFrom?: T;
  validUntil?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  business?: T;
  name?: T;
  price?: T;
  image?: T;
  description?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-listings_select".
 */
export interface CarListingsSelect<T extends boolean = true> {
  title?: T;
  make?: T;
  model?: T;
  year?: T;
  price?: T;
  mileage?: T;
  engine?: T;
  transmission?: T;
  fuelType?: T;
  drivetrain?: T;
  bodyType?: T;
  exteriorColor?: T;
  vin?: T;
  description?: T;
  photos?: T;
  sellerName?: T;
  sellerPhone?: T;
  dealer?: T;
  slug?: T;
  status?: T;
  isFeatured?: T;
  bumpedAt?: T;
  expiresAt?: T;
  source?: T;
  isDemo?: T;
  slugHistory?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-makes_select".
 */
export interface CarMakesSelect<T extends boolean = true> {
  name?: T;
  models?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  business?: T;
  companyName?: T;
  category?: T;
  employmentType?: T;
  workMode?: T;
  salaryMin?: T;
  salaryMax?: T;
  salaryPeriod?: T;
  location?: T;
  description?: T;
  summary?: T;
  howToApply?: T;
  openTo?: T;
  perks?: T;
  languages?: T;
  isUrgent?: T;
  isFeatured?: T;
  slug?: T;
  status?: T;
  expiresAt?: T;
  source?: T;
  isDemo?: T;
  slugHistory?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-categories_select".
 */
export interface JobCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startAt?: T;
  endAt?: T;
  category?: T;
  venueName?: T;
  address?: T;
  lat?: T;
  lng?: T;
  geocodeNote?: T;
  isFree?: T;
  price?: T;
  ticketUrl?: T;
  image?: T;
  summary?: T;
  description?: T;
  slug?: T;
  status?: T;
  isDemo?: T;
  slugHistory?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-categories_select".
 */
export interface EventCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contests_select".
 */
export interface ContestsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  rules?: T;
  startAt?: T;
  endAt?: T;
  entries?:
    | T
    | {
        image?: T;
        title?: T;
        participantFirstName?: T;
        participantAge?: T;
        parentConsent?: T;
        id?: T;
      };
  slug?: T;
  status?: T;
  isDemo?: T;
  slugHistory?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  businessName?: T;
  category?: T;
  desiredPackage?: T;
  desiredSlot?: T;
  photos?: T;
  location?: T;
  internalNotes?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-slots_select".
 */
export interface AdSlotsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  page?: T;
  position?: T;
  desktopSize?: T;
  mobileSize?: T;
  weeklyPrice?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  advertiser?: T;
  linkUrl?: T;
  slots?: T;
  imageDesktop?: T;
  imageMobile?: T;
  startAt?: T;
  endAt?: T;
  status?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner-stats_select".
 */
export interface BannerStatsSelect<T extends boolean = true> {
  banner?: T;
  date?: T;
  impressions?: T;
  clicks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  content?: T;
  blocks?:
    | T
    | {
        content?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              text?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  status?: T;
  isDemo?: T;
  slugHistory?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  isDemo?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  url?: T;
  excerpt?: T;
  kind?: T;
  keywords?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Default description for search engines and link previews.
   */
  description?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  /**
   * Leave empty to show "Coming soon" on the site.
   */
  socials?: {
    instagram?: string | null;
    facebook?: string | null;
  };
  /**
   * G-XXXXXXX. Loaded only after a visitor accepts cookies.
   */
  ga4MeasurementId?: string | null;
  /**
   * The content value of the google-site-verification meta tag.
   */
  searchConsoleVerification?: string | null;
  /**
   * Where new submissions are announced (needs TELEGRAM_BOT_TOKEN).
   */
  telegramChatId?: string | null;
  /**
   * Email copy of new submissions (needs RESEND_API_KEY).
   */
  notifyEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Panorama at the top of every page. Empty = the built-in Seattle skyline.
   */
  heroImage?: (number | null) | Media;
  /**
   * Main menu. "Primary" items form the top row with icons; "Secondary" items the smaller row under it (on phones both rows scroll as one).
   */
  menu?:
    | {
        label: string;
        url: string;
        row: 'primary' | 'secondary';
        icon?: ('none' | 'home' | 'news' | 'directory' | 'advertising' | 'cars') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short labelled links in a strip under the menu.
   */
  announcements?:
    | {
        /**
         * e.g. Contest
         */
        label: string;
        text: string;
        url: string;
        /**
         * Accent colour — use for the one thing that matters most.
         */
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Link columns. Contacts and socials come from Site settings.
   */
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The © and the current year are added automatically.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  phone?: T;
  email?: T;
  address?: T;
  socials?:
    | T
    | {
        instagram?: T;
        facebook?: T;
      };
  ga4MeasurementId?: T;
  searchConsoleVerification?: T;
  telegramChatId?: T;
  notifyEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  heroImage?: T;
  menu?:
    | T
    | {
        label?: T;
        url?: T;
        row?: T;
        icon?: T;
        id?: T;
      };
  announcements?:
    | T
    | {
        label?: T;
        text?: T;
        url?: T;
        highlight?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}